name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GO111MODULE: on
  BUILDKIT_HOST: docker-container://buildkitd

jobs:
  build:
    name: Build
    runs-on: buildkitd
    steps:
    - name: Set up Go 1.13.10
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.10
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go get

    - name: Compile
      run: |
        go build -o build/hlb ./cmd/hlb
        go build -o build/docgen ./cmd/docgen
        go build -o build/builtingen ./cmd/builtingen

    - name: Go Tests
      run: go test -v ./...

    - name: GoLint
      run: ./build/hlb run -t lint

    - name: Ensure generated files
      run: |
        ./build/hlb run -t gen
        if ! git diff --quiet; then
          echo "ERROR: Generated files need updating:" >&2
          echo "" >&2
          git ls-files -m | sed 's/^/	/g' >&2
          echo "" >&2
          echo "To resolve run:" >&2
          echo "	./hlb run -t gen" >&2
          echo "and add changes to the git branch" >&2
          exit 1
        fi

    - name: Crosscompile
      run: ./build/hlb run