name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GO111MODULE: on

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go get

    - name: Compile
      run: |
        go build -o build/hlb ./cmd/hlb
        go build -o build/frontend ./cmd/frontend
        go build -o build/docgen ./cmd/docgen
        go build -o build/builtingen ./cmd/builtingen

    - name: Go Tests
      run: go test -v ./...
      
    - name: Start BuildkitD
      run: docker run --name buildkitd --rm -d --privileged openllb/buildkit:experimental

    - name: BuildkitD Wait
      # waiting for buildkitd to report 1 worker (2 lines, 1 for column titles, one for the worker details)
      run: while true; do lineCount=$(docker exec buildkitd buildctl debug workers | wc -l); if [ $lineCount -gt 1 ]; then break; fi; sleep 1; done

    - name: GoLint
      run: ./build/hlb --addr docker-container://buildkitd run --log-output plain -t lint ./source.hlb

    - name: Crosscompile
      run: ./build/hlb --addr docker-container://buildkitd run --log-output plain ./source.hlb


